import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import LandingPage from "../components/LandingPage";
import DarkMode from "../components/DarkMode";

export async function getStaticProps() {
  const response = await axios.get("http://localhost:3000/api/profile");
  const profile = await response.data;
  return {
    props: { profile },
  };
}

export default function Home({ profile }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{profile[0].job}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="profile">
        <LandingPage profile={profile} />
      </div>
      <DarkMode />
    </div>
  );
}
